version: '3'

services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: "pgadmin4"
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=support@smlsoft.com"
      - "PGADMIN_DEFAULT_PASSWORD=smlsupport"
      - "SCRIPT_NAME=/pgadmin4"
    networks:
      - backend
    labels:
      # - "traefik.http.routers.pgadmin4.rule=(Host(`host.com`) && PathPrefix(`/pgadmin4`))"
      - "traefik.http.routers.pgadmin4.rule=(PathPrefix(`/pgadmin4`))"

networks:
  backend:
    external:
      name: sml_service_network