version: '3'

services:
  traefik:
    image: traefik:v2.3
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.watch"
      - "--entrypoints.web.address=:80"
#      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
#      - "--log.level=DEBUG"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.api.rule=(Host(`host.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`)))"
      - "traefik.http.routers.api.rule=((PathPrefix(`/api`) || PathPrefix(`/dashboard`)))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=toe:$$apr1$$9dmswe8v$$k1RQ.WAI57gWWHD.l/.dV1,sml:$$apr1$$ia38r5sb$$8uxrh4fGN.OOFjdhB9FNW0"
      - "traefik.http.middlewares.auth.basicauth.removeheader=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 80:80
      - 8080:8080
    networks:
      - frontend

networks:
  frontend:
    external:
      name: sml_service_network
